### ISSUE TITLE
Enable copying of field information

### ISSUE THREAD

**Issue by Viba** [FAForever/faf-moderator-client#50] opened 2018-06-19 15:40 UTC
Being able to copy information such as nickname, IP and other fields would improve moderation workflow in mordor significantly.

e.g. right clicking a certain field could copy said field into your clipboard, or the field information could be non-editable but selectable and thus copyable.

**Comment by axel1200** [comment] 2018-06-19 20:32
Not that easy

**Comment by axel1200** [comment] 2018-07-01 11:30
If you give me a list of colums you like to have copiable a guess I can do that but doing ot for all 🤔 hard, I can make you a menu that says "copy username" on right click, i can make the clummn editabe but so that you can not change the text. I dont know how that would work otherwise

**Comment by axel1200** [comment] 2018-07-01 11:32
duplicate of #32

**Comment by axel1200** [comment] 2018-07-01 11:32
@speed2CZ

**Comment by Viba** [comment] 2018-07-01 18:30
Well ideally all fields in the user management view. Most used ones would be nickname and IP.

**Comment by axel1200** [comment] 2018-07-02 18:43
Will make you a copy nickname /ip then. Maybe somebody comes up with an idea how to do it in general. I mean I you could right click copy data and I could ask you which column you want. Because I i am missing that information.

**Comment by axel1200** [comment] 2018-07-02 18:44
And It seems hard to find out what column you right clicked on

**Comment by axel1200** [comment] 2018-07-02 19:15
![image](https://user-images.githubusercontent.com/19996713/42181962-06bed13c-7e3d-11e8-85be-3c4e78be5baa.png)

**Comment by axel1200** [comment] 2018-07-02 19:19
![image](https://user-images.githubusercontent.com/19996713/42182145-942d5ab6-7e3d-11e8-9e98-9623c01514e7.png)
Well apart from that a dont have teamkills in my test data

**Comment by axel1200** [comment] 2018-07-02 19:19
![image](https://user-images.githubusercontent.com/19996713/42182178-ab0bb4bc-7e3d-11e8-8f2c-5589a6c289ed.png)

**Closed** 2018-07-11 23:03 UTC
